apiVersion: v1
kind: Service
metadata: 
  name: nglb 
spec:
  selector:
    app: nginx
  type: LoadBalancer
  #  externalIPs:
  #- 3.81.227.201
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000


