apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1Ea3pNREF4TWpnME4xb1hEVE14TURreU9EQXhNamcwTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTktuCm84Y0toVjA4c0M1eklCeWUxRzd4OWswRTBudlRENzdJOGJzWHNENkJsSWxqUTRML1hEaHBseXF0eEtWeXVMWWEKQ01keVMxMnh2R1ZUaDhReWthb1Y3SHlrYkpHbkdGMFZnd3p0MEpKYkVCR213dlVqUVN0MmVuVXc4SE9sZnp6eAppM2E1V0ZYVGJHeXZrUi81d1RIdmdiL25kQXFIbGloMnhKRndtODdUZEY3bFhTSTV0MnlDckdVWTZHZDc0ZXlUCkdLM2FGZDFmTDB0bGJ2VHJGamtSZ3dXYXJhcEhkVm5QU3VqazBmYmNYTm4vSG5wTVluV1dqUkhEYWlpb284YmkKNXR5OVM2SlNFUFc2YU91bCtNNkJZdWE1ZVRpcnBBQXZjLzB6V2FjZVFIV2lIc3BFOXJ1V0dYTkVna1ZnaUFuWgpxYTJjMldBbXVjYkIzMTFGdktFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGSGVwU25YTEE2alVFNEpabmhnc0RCVHVHRnJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRjhlNzUyYjFONDVFQkF0aVZxdgpHTzNqVVIzMzNCZjcwNE1URXFiWHRYSTVUNTlDbnlQN3FCVkZEMDVrdmV4RmN1ZXg2THZzUTJMa0VBK2RmUThVClJiM0wwdVVXRUV2MTNqMWVZb2JJOWt3QldBdFFkY0V6NlhLc2JoNjA2c2YyR04xdnVLNlZlcjdXZkM0U08rcnAKQThxcmxmeE5veXRrUlk5V0ZGcTZaSWZmbVdmd2hhVmhyclphdFZmTFJFVDNxMjZDeThNZFBVemJFdUt3UDVMWgorNnJRVmQvNlRTdmgwOXU5TFBYWlZ0YWV3dUJHNml4bndacklUZis1UVFJamxZRkJ1VzV1aEFqUGltTnBGS0Y4Cng4S01LVHVmdUJLTWZ6cUtiWW13SGJibUhHNzBOWXJGT3FDVnFPQ0pyeThwQjdBbnR4Q0dCTXg5dTA4RGZicTMKdXA0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://172.31.46.148:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-30T01:29:00Z"
  name: cluster-info
  namespace: kube-public
  resourceVersion: "2408"
  uid: cd103032-516a-476c-9ded-6b58a1c1d2a7
