---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-demo
spec:
  selector:
    matchLabels:
      app: alpine
  template:
      metadata:
        labels: 
          app: alpine
      spec:
        containers:
          - name: alpine
            image: alpine
            args: 
              - /bin/bash
              - -c
              - sleep 1d


            
