---
apiVersion: v1
kind: Pod
metadata: 
  name: gol
spec:
  containers:
    - image: qualitythought.in/gameoflife:07112020
      name: golqt
      ports: 
        - containerPort: 8080
          name: golqthttp
          protocol: TCP
           