---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gol
spec: 
#  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: gol
    #env: dev
  template: 
    metadata: 
      labels:
        app: gol
        #version: "160621"
        #env: dev
    spec:     
      containers:
      - image: qualitythought/gameoflife:07112020
        name: gol
        ports:
          - containerPort: 8080
            protocol: TCP

