apiVersion: v1
kind: Service   
metadata:
  name: nginxash
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
        #  type: NodePort
  type: LoadBalancer
  selector:
    app: nginx
    createdby: ashish
    run: nginx
  ports:
    - protocol: TCP
      #      nodePort: 31200
      targetPort: 8080
      port: 8080
  externalIPs:
    - 54.164.201.248
