---
apiVersion: v1 
kind: Pod
metadata:
  name: resourcelimit-demo
  labels:
    name: resourcelimit-demo
    env: dev
spec:
  containers:
  - name: cont-with-limits
    image: nginx
    resources:
      limits:
        memory: "512M"
        cpu: "1"
      requests:
        memory: "64M"
        cpu: "0.5"
    ports:
      - containerPort: 80
        protocol: TCP
        name: limitport 
