---
apiVersion: v1
kind: Pod
metadata: 
  name: spc
  namespace: dev
spec:
  containers:
    - image: springcommunity/spring-petclinic-visits-service
      name: spc
      ports:
        - containerPort: 8080
          name: spcport
          protocol: TCP
