---
apiVersion: v1
kind: Service
metadata:
  name: spcsvc
spec:
  selector:
    environment: dev
    app: spc
  type: NodePort
  ports: 
    - targetPort: 8080
      port: 8080
      nodePort: 32500



 
